bitfinexcom/bfx-report

- workers/loc.api/queue/helpers.js
This PR improves wallets export name
Actually: username_wallets_FROM_Tue-Oct-16-2018_TO_Tue-Jan-08-2019_ON_2019-01-16T15-06-41.803Z.zip
It should be: username_wallets_MOMENT_Mon-Jan-14-2018.zip
> Improve wallets export name

- test/2-sync-mode-sqlite.spec.js
- test/3-queue-base.spec.js
- test/4-queue-load.spec.js
- test/helpers/helpers.tests.js
- workers/api.service.report.wrk.js
- workers/loc.api/errors/index.js
- workers/loc.api/helpers/get-csv-job-data.js
- workers/loc.api/helpers/getCsvJobData.js
- workers/loc.api/helpers/index.js
- workers/loc.api/helpers/schema.js
- workers/loc.api/queue/aggregator.js
- workers/loc.api/queue/helpers.js
- workers/loc.api/queue/processor.js
- workers/loc.api/service.report.js
This PR adds the ability to export more than one `csv` file at a time with a single call to the `getMultipleCsv` method
Example:
- call the `getMultipleCsv` method and pass params array:
```
{
"auth": {
"apiKey": "fake",
"apiSecret": "fake"
},
"method": "getMultipleCsv",
"params": {
"email": "fake@email.fake",
"multiExport": [
{
"method": "getTradesCsv",
"symbol": "tBTCUSD",
"end": 1546765168000
},
{
"method": "getLedgersCsv",
"symbol": "BTC",
"end": 1546765168000,
"timezone": "America/Los_Angeles"
}
]
}
}
```
- if `syncMode: false` in `config/service.report.json` then all files will be zipped and emailed:
`username_multiple-exports_MOMENT_2019-01-16T15-06-41.803Z.zip`
- if `syncMode: true` in `./config/service.report.json` then all files will be saved locally in `./csv` directory: …
> Add ability to export more than one `csv` file at a time

- workers/loc.api/sync/dao/dao.sqlite.js
- workers/loc.api/sync/data.inserter.js
- workers/loc.api/sync/schema.js
Funding earnings is an old report feature that was available before. There is no `api` endpoint for this.
This PR adds the ability to generate the report by filtering the ledgers starting with `Margin Funding Payment` in the description field for users using sync mode only. It adds `_isMarginFundingPayment` field to DB as to do searches faster
Examples:
- get ledgers starting with `Margin Funding Payment` in the description field
```
{
"auth": {
"apiKey": "fake",
"apiSecret": "fake"
},
"method": "getLedgers", // or getLedgersCsv
"params": {
"symbol": "BTC",
"isMarginFundingPayment": true
}
}
```
- get ledgers starting without `Margin Funding Payment` in the description field
```
{
"auth": {
"apiKey": "fake",
"apiSecret": "fake"
},
"method": "getLedgers", // or getLedgersCsv
"params": { …
```
> Add ability to filter ledgers starting with "Margin Funding Payment" in description field

- test/helpers/helpers.mock-rest-v2.js
- workers/loc.api/service.report.mediator.js
- workers/loc.api/sync/allowed.colls.js
- workers/loc.api/sync/dao/dao.sqlite.js
- workers/loc.api/sync/data.inserter.js
- workers/loc.api/sync/schema.js
This PR adds `wallets` to the sync mode.
The `api_v2` `wallets/hist` endpoint returns the history of the wallet in the 00:00:00 (`HH:MM:SS`) UTC of a certain data.
For the first time running the sync wallets, we should sync stepping by date with an interval of 24 hours `currIterationArgs.params.end = currIterationArgs.params.end - 24h`. And if the user makes a request with precision `HH:MM:SS` then we need to respond with `wallets` data adding the missing part from `ledgers`
> Add wallets to sync mode

- workers/loc.api/queue/helpers.js
This PR fixes exported csv file name. When exporting one file there was the name as if it was a multiple export
> Fix exported csv file name

- workers/loc.api/helpers/get-csv-job-data.js
This PR adds `transactionId` field to movements (deposits and withdrawals) csv
> Add transactionId field to movements csv

- workers/loc.api/errors/index.js
- workers/loc.api/sync/data.inserter/api.middleware.js
- workers/loc.api/sync/data.inserter/helpers/filter-method-coll-map-by-list.js
- workers/loc.api/sync/data.inserter/helpers/index.js
- workers/loc.api/sync/data.inserter/helpers/search-close-price-and-sum-amount.js
- workers/loc.api/sync/data.inserter/helpers/utils.js
- workers/loc.api/sync/data.inserter/index.js
This PR splits the `DataInserter` module `workers/loc.api/sync/data.inserter` into different helper modules and moves errors to errors module
* With this PR need to merge this PR: [bitfinexcom/bfx-reports-framework#3](https://github.com/bitfinexcom/bfx-reports-framework/pull/3)
> Refactor DataInserter

- workers/loc.api/errors/index.js
This PR adds custom method access error `DuringSyncMethodAccessError` when sync is not complete, to the errors module
> Add custom method access error

- workers/loc.api/service.report.mediator.js
This PR adds an ability to throw `DuringSyncMethodAccessError` error when `getLedgers()` method is called with `isMarginFundingPayment: true` param if sync is not completed
> Throw DuringSyncMethodAccessError error in getLedgers method if isMarginFundingPayment: true

- test/helpers/mock-data.js
- workers/loc.api/service.report.js
- workers/loc.api/service.report.mediator.js
This PR fixes async response return of the `getWallets` method
And small fixes mock data of the symbols, it is related to this changing [bfx-api-node-rest](https://github.com/bitfinexcom/bfx-api-node-rest/pull/24/commits/bd80067e7a98b1678f47585771667e1b28f98bb2), and depends on this PR [bfx-api-mock-srv](https://github.com/bitfinexcom/bfx-api-mock-srv/pull/17)
> Fix getWallets async response return

- test/helpers/helpers.mock-rest-v2.js
This PR changes the `helpers.mock-rest-v2` to add tests to the `bfx-reports-framework`
> Change mock-rest-v2 helpers to add tests to bfx-reports-framework

- test/1-api.spec.js
- test/2-sync-mode-sqlite.spec.js
- test/helpers/helpers.mock-rest-v2.js
- test/helpers/mock-data.js
- workers/loc.api/sync/dao/dao.sqlite.js
- workers/loc.api/sync/schema.js
This PR fixes currencies sync. The issue is related: when the next sync is done then currencies will be added into DB as new rows. In this case, should refresh rows or `add`/`remove` if `not exist in the DB`/`not exist from API`. **Depends** on this PR [bfx-api-mock-srv#18](https://github.com/bitfinexcom/bfx-api-mock-srv/pull/18)
> Fix currencies sync

- test/1-api.spec.js
- test/2-sync-mode-sqlite.spec.js
- test/3-queue-base.spec.js
- test/helpers/helpers.mock-rest-v2.js
- test/helpers/mock-data.js
- workers/loc.api/helpers/get-csv-job-data.js
- workers/loc.api/queue/helpers.js
- workers/loc.api/service.report.js
This PR adds the [active orders](https://docs.bitfinex.com/v2/reference#rest-auth-orders) report without sync. Base changes:
- adds `getActiveOrders` method
- adds `getActiveOrdersCsv` method
- adds `typePrev` and `priceTrailing` fields to `getOrdersCsv` method
- improves tests coverage
> Add active orders report

- test/1-api.spec.js
- test/2-sync-mode-sqlite.spec.js
- test/3-queue-base.spec.js
- test/helpers/helpers.mock-rest-v2.js
- test/helpers/mock-data.js
- workers/loc.api/helpers/get-csv-job-data.js
- workers/loc.api/helpers/limit-param.helpers.js
- workers/loc.api/helpers/prepare-response.js
- workers/loc.api/queue/helpers.js
- workers/loc.api/service.report.js
- workers/loc.api/service.report.mediator.js
- workers/loc.api/sync/allowed.colls.js
- workers/loc.api/sync/schema.js
This PR adds the funding trades report. Base changes:
- adds `getFundingTrades` method
- adds `getFundingTradesCsv` method
- adds funding trades to sync mode
- adds tests coverage of `getFundingTrades` and `getFundingTradesCsv` methods
**Depends** on this PR [bfx-api-mock-srv#19](https://github.com/bitfinexcom/bfx-api-mock-srv/pull/19)
> Add funding trades report

- package.json
This PR hardcodes `sqlite3` `4.0.3` version in the `package.json`
An issue related with the following:
- when we use `group by` and `order by` clauses together that the `sqlite3` driver `4.0.6` version returns the wrong result
> Hardcode sqlite3 version

- package.json
- workers/loc.api/service.report.mediator.js
- workers/loc.api/sync/allowed.colls.js
- workers/loc.api/sync/dao/dao.sqlite.js
- workers/loc.api/sync/dao/helpers/get-group-query.js
- workers/loc.api/sync/dao/helpers/get-insertable-array-objects-filter.js
- workers/loc.api/sync/dao/helpers/get-sub-query.js
- workers/loc.api/sync/dao/helpers/index.js
- workers/loc.api/sync/data.inserter/index.js
- workers/loc.api/sync/schema.js
This PR changes receiving wallets logic for the sync mode. Base changes:
- removes wallets sync of the `api_v2`
- changes receiving of wallets, now all data is taken from ledgers table
- adds an ability to execute sub-query for sorting before grouping to the `findInCollBy` method of the `SqliteDAO`. This is necessary because we have rows with equal timestamp values (`mts` field) and need to sort data by `mts` and `id` fields before grouping
- adds data structure converter to the schema for wallets from ledgers to be able to override this converter in the `bfx-reports-framework`
**Depends** on this PR [bitfinexcom/bfx-report#122](https://github.com/bitfinexcom/bfx-report/pull/122)
> Change receiving wallets logic for sync mode

- workers/loc.api/service.report.mediator.js
- workers/loc.api/sync/dao/dao.sqlite.js
This PR adds an ability to override schema to the `findInCollBy` method of the `SqliteDAO`.
This change is necessary for [bfx-reports-framework#15](https://github.com/bitfinexcom/bfx-reports-framework/pull/15)
> Add ability to override schema to findInCollBy method of SqliteDAO

- package.json
- workers/loc.api/helpers/api-errors-testers.js
- workers/loc.api/queue/helpers.js
This PR fixed the `isRateLimitError` helper. The production `api_v2` server is responded different error message `RateLimit` for the candles endpoint:
```
statusCode: 429
name: StatusCodeError
message: 429 - ["error",11010,"ratelimit: error"]
options: {"url":"https://api.bitfinex.com/v2/candles/trade:1D:tETHUSD/hist?limit=500&start=1502323200000&end=1514332800000","method":"GET","timeout":15000,"json":true,"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}
```
> Fix isRateLimitError helper

- workers/loc.api/sync/dao/dao.sqlite.js
This PR adds an `isExcludePrivate` option to the `findInCollBy` method of the `SqliteDAO`, in order to be able to exclude or include private fields to a DB selection
> Add isExcludePrivate to findInCollBy method of SqliteDAO

- test/1-api.spec.js
- test/2-sync-mode-sqlite.spec.js
- test/helpers/helpers.mock-rest-v2.js
- test/helpers/mock-data.js
- workers/loc.api/service.report.mediator.js
- workers/loc.api/sync/allowed.colls.js
- workers/loc.api/sync/schema.js
This PR adds support for futures to sync mode. Basic changes:
- adds support for futures to sync mode
- adds futures mock data
- change tests to support futures
**Depends** on this PR [bitfinexcom/bfx-api-mock-srv#18](https://github.com/bitfinexcom/bfx-api-mock-srv/pull/18)
> Add support for futures to sync mode

- package.json
- workers/loc.api/queue/helpers.js
- workers/loc.api/queue/processor.js
- workers/loc.api/service.report.js
- workers/loc.api/sync/dao/helpers/get-where-query.js
This PR adds minor changes for adding a account snapshot report to the [bfx-reports-frameworks](https://github.com/bitfinexcom/bfx-reports-framework). Basic changes:
- adds `gte` and `lte` clauses to the `DAO`
- adds async handling to the `getPositionsAudit` method
- adds `csvCustomWriter` to the `processor` queue
- bumps csv module version to `5.1.1`
- adds to exports `write` and `getDataFromApi` modules in queue helpers module
- adds an ability to pass a flag for generating of a file name with `current moment` timestamp
> Add minor changes for adding account snapshot report

- package.json
- test/1.1-report-signature.spec.js
- test/3-queue-base.spec.js
- test/helpers/helpers.tests.js
- test/helpers/helpers.worker.js
- test/simulate/mocks-spies/gpg.js
- workers/api.service.report.wrk.js
- workers/loc.api/helpers/check-job-and-get-user-data.js
- workers/loc.api/helpers/grc-bfx-req.js
- workers/loc.api/helpers/index.js
- workers/loc.api/helpers/schema.js
- workers/loc.api/queue/aggregator.js
- workers/loc.api/queue/helpers.js
- workers/loc.api/queue/processor.js
- workers/loc.api/queue/translations/email.yml
- workers/loc.api/queue/views/email.pug
- workers/loc.api/service.report.js
- workers/loc.api/service.report.mediator.js
- workers/loc.api/sync/dao/dao.sqlite.js
- workers/loc.api/sync/schema.js
This PR adds an ability to sign reports by PGP signature. Basic changes:
- adds `verifyDigitalSignature` method
- implements reports signing by PGP signature before reports uploading to `S3` using this service [bfx-ext-sendgrid-js](https://github.com/bitfinexcom/bfx-ext-gpg-js)
- improves email template
-  adds corresponding test coverage
**Depends** on this PR [bitfinexcom/bfx-ext-gpg-js#1](https://github.com/bitfinexcom/bfx-ext-gpg-js/pull/1)
**TODO**: need to add zh-CN and zh-TW translations
> Add ability to sign reports by PGP signature

- test/1-api.spec.js
- test/2-sync-mode-sqlite.spec.js
- test/3-queue-base.spec.js
- test/helpers/helpers.mock-rest-v2.js
- test/helpers/mock-data.js
- workers/loc.api/helpers/get-csv-job-data.js
- workers/loc.api/helpers/limit-param.helpers.js
- workers/loc.api/helpers/prepare-response.js
- workers/loc.api/helpers/schema.js
- workers/loc.api/queue/helpers.js
- workers/loc.api/service.report.js
- workers/loc.api/service.report.mediator.js
- workers/loc.api/sync/dao/helpers/get-insertable-array-objects-filter.js
This PR adds order trades which can get by order id. Basic changes:
- adds `getOrderTrades` method
- adds `getOrderTradesCsv` method
- adds `getOrderTrades` method to the sync mode
> Add order trades

- workers/loc.api/queue/write-data-to-stream/helpers.js
This PR changes symbols formatting for csv generating
This cover these situations:
- `BTCF0:USTF0` => `BTCF0/USTF0`
- `tBTCF0:USTF0` => `BTCF0/USTF0`
- `tBTCF0` => `BTCF0`
- `BTCF0` => `BTCF0`
- `tBTCUSD` => `BTC/USD`
- `BTCUSD` => `BTCUSD`
- `tBTC` => `BTC`
- `BTC` => `BTC`
> Change symbols formatting for csv generating

- test/1-api.spec.js
- workers/loc.api/helpers/prepare-response.js
This PR improves max limit handling for movements. If limit sent is === to MAX LIMIT, instead of returning a response that the limit should be bigger, will return the response anyway
> Improve max limit handling for movements

- test/1-api.spec.js
- test/helpers/mock-data.js
- workers/loc.api/generate-csv/csv.job.data.js
This PR adds `meta`, `collateral`, `collateralMin` fields to the positions audit report
> Add meta and collateral fields to positions audit

- test/1-api.spec.js
- test/4-queue-base.spec.js
- test/helpers/helpers.mock-rest-v2.js
- test/helpers/mock-data.js
- workers/loc.api/generate-csv/csv.job.data.js
- workers/loc.api/helpers/prepare-response.js
- workers/loc.api/helpers/schema.js
- workers/loc.api/service.report.js
This PR adds status messages report. Basic changes:
- adds `getStatusMessages` method to the main service
- adds `getStatusMessagesCsv` method to the main service
Example of a request:
```js
{
"auth": {
},
"method": "getStatusMessagesCsv",
"params": {
"type": "deriv", // by default
"symbol": ["tBTCF0:USTF0", "tETHF0:USTF0"],  // ['ALL'] by default
}
}
```
> Add status messages report

- test/1-api.spec.js
- test/2-api-filter.spec.js
- workers/loc.api/queue/write-data-to-stream/helpers.js
- workers/loc.api/queue/write-data-to-stream/index.js
This PR fixes movements filtering:
- fixes the following issue, when the `nextPage` field (in response) is an integer but the data array is empty export csv is not gone to the next page
- fixes test cases for the `getPositionsAudit` and `getWallets` methods related to the changes of [bfx-api-node-models](https://github.com/bitfinexcom/bfx-api-node-models/commit/b2af1131f8a225d994e7473c3782385c05e4e6d6#diff-3f88a395e968f1aeeac7d06262610561L16)
> Fix movements filtering

- workers/loc.api/helpers/prepare-response.js
This PR fixes second call request condition to the `api_v2`, do not make a second call with max limit to the `api_v2` if the first call is empty
> Fix second call request condition to api_v2

- package.json
- workers/api.service.report.wrk.js
- workers/loc.api/logger/index.js
- workers/loc.api/queue/helpers/utils.js
This PR adds an ability to specify paths to csv folder, temporary csv folder, logs folder, dbs of lokue queues
**Depends** on this PR [bfx-facs-lokue#3](https://github.com/bitfinexcom/bfx-facs-lokue/pull/3)
> Add ability to specify paths to writing files

- workers/api.service.report.wrk.js
This PR changes the property name of the absolute path to db
**Depends** on this commit of `PR#3`: [bfx-facs-lokue#3](https://github.com/bitfinexcom/bfx-facs-lokue/pull/3/commits/c8cbc55aa718f1cfdabd21f5bb3ed2945040a28b)
> Change db absolute path property name

- package.json
- test/1-api.spec.js
- test/helpers/mock-data.js
- workers/loc.api/service.report.js
This PR adds an account summary endpoint that always returns information from the api. Basic changes:
- bumps `bitfinex-api-node` version up to `4.0.3`
- adds `getAccountSummary` method to the main service
- adds corresponding account summary test coverage
- bumps version up to `2.2.2`
Example of request:
```json
{
"auth": {
},
"method": "getAccountSummary"
}
```
Example of response:
```json
{
"result": {
"time": "2020-02-10T06:49:30.270Z",
"status": {
"resid_hint": null
},
"is_locked": false,
"trade_vol_30d": [
{
"curr": "BTC",
"vol": 0.12345
},
{
"curr": "ETH",
"vol": 0.12345
},
{
"curr": "BTCF0",
"vol": 0.12345
},
{
"curr": "Total (USD)",
"vol": 12345.12345,
"vol_maker": 12345.12345,
"vol_BFX": 12345.12345,
"vol_BFX_maker": 12345.12345
}
], …
```
> Add account summary

- package.json
- test/1-api.spec.js
- test/4-queue-base.spec.js
- test/helpers/helpers.mock-rest-v2.js
- test/helpers/mock-data.js
- workers/loc.api/generate-csv/csv.job.data.js
- workers/loc.api/helpers/filter-models.js
- workers/loc.api/helpers/filter.models.names.js
- workers/loc.api/helpers/index.js
- workers/loc.api/helpers/limit-param.helpers.js
- workers/loc.api/helpers/prepare-response.js
- workers/loc.api/helpers/utils.js
- workers/loc.api/service.report.js
This PR adds a logins endpoint. Basic changes:
- adds `getLogins` method to the main service
- adds `getLoginsCsv` method to the main service
- adds corresponding test coverage of logins
- adds filter model for logins
- bumps version up to `2.2.3`
Example of request:
```json
{
"auth": {
},
"method": "getLogins",
"params": {
"end": 1575249855000,
"start": 1572566400000,
"limit": 2
}
}
```
Example of response:
```json
{
"result": {
"res": [
{
"_isDataFromApiV2": true,
"id": 12345,
"time": 1575195432000,
"ip": "127.0.0.1",
"extraData": {
"asn": "12345, Google LLC",
"geo": "Unknown, SG",
"user_agent": {
"os": "Linux x86_64",
"raw": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36",
"browser": …
```
> Add logins

- package.json
- workers/loc.api/errors/index.js
- workers/loc.api/helpers/prepare-response.js
This PR adds an ability to filter ledgers by funding and affiliate payments to the hosted version:
- Example of request:
```js
{
"auth": {
},
"method": "getLedgers",
"params": {
"end": 1575249855000,
"start": 1572566400000,
"limit": 2,
"symbol": "USD",
"isMarginFundingPayment": true // or "isAffiliateRebate": true
}
}
```
- Example of response:
```json
{
"result": {
"res": [
{
"id": 123456789,
"currency": "USD",
"mts": 1575163809000,
"amount": 1.2345,
"amountUsd": 5.4321,
"balance": 12345.12345,
"balanceUsd": 54321.54321,
"description": "Margin Funding Payment on wallet funding",
"wallet": "funding"
}
],
"nextPage": false
},
"id": null
}
```
> Add funding and affiliate payments to hosted version

- package.json
- test/1-api.spec.js
- test/4-queue-base.spec.js
- test/helpers/helpers.mock-rest-v2.js
- test/helpers/mock-data.js
This PR removes redundant test coverage of the `getWallets` endpoint
These changes are related to this PR [bfx-report#171](https://github.com/bitfinexcom/bfx-report/pull/171)
> Remove redundant test coverage of wallets

- package.json
- test/1-api.spec.js
- workers/loc.api/service.report.js
This PR adds an ability to return account summary array instead of an object. This is required for sub-accounts to return an array of objects of all sub-users related to sub-account
> Return account summary array instead of object

- test/1-api.spec.js
- test/4-queue-base.spec.js
- test/helpers/helpers.mock-rest-v2.js
- test/helpers/mock-data.js
- workers/loc.api/generate-csv/csv.job.data.js
- workers/loc.api/helpers/filter-models.js
- workers/loc.api/helpers/filter.models.names.js
- workers/loc.api/helpers/limit-param.helpers.js
- workers/loc.api/helpers/prepare-response.js
- workers/loc.api/queue/helpers/get-complete-file-name.js
- workers/loc.api/service.report.js
This PR adds changeLogs endpoints. Basic changes:
- adds `getChangeLogs` method to the main service
- adds `getChangeLogsCsv` method to the main service
- https://github.com/bitfinexcom/bfx-report/pull/174
> Add changeLogs endpoint

- workers/loc.api/helpers/prepare-response.js
This PR adds an ability to filter staking payments on ledgers using `"isStakingPayments": true` param in a request to the `getLedgers` method
- https://github.com/bitfinexcom/bfx-report/pull/174
> Add staking payments

- test/1-api.spec.js
- test/helpers/helpers.mock-rest-v2.js
- test/helpers/mock-data.js
- workers/loc.api/service.report.js
This PR adds inactive symbols https://github.com/bitfinexcom/bfx-api-node-rest/pull/70 to `getSymbols` method
- https://github.com/bitfinexcom/bfx-report/pull/174
- https://github.com/bitfinexcom/bfx-api-mock-srv/pull/36
> Add inactive symbols

- test/helpers/mock-data.js
This PR adds mock data for currency `walletFx` field
**Depends** on these PRs:
- https://github.com/bitfinexcom/bfx-api-node-models/pull/53
- https://github.com/bitfinexcom/bfx-api-node-rest/pull/72
> Add mock data for currency walletFx

- test/1-api.spec.js
- workers/loc.api/service.report.js
This PR removes `/check-stored-locally` endpoint supporting
- https://github.com/bitfinexcom/bfx-report-express/pull/11
> Remove check-stored-locally endpoint

- workers/loc.api/helpers/prepare-response.js
This PR reduces the response payload. The issue is in response of the `getPositionsAudit` method was noticed redundant `_apiInterface` object which one is proxied from the `bitfinex-api-node`:
```json
"_apiInterface": {
"_url": "https://api-pub.bitfinex.com",
"_apiKey": "---",
"_apiSecret": "---",
"_authToken": "",
"_company": "bitfinex",
"_transform": true,
"_rest1": {
"_url": "https://api-pub.bitfinex.com",
"_apiKey": "---",
"_apiSecret": "---"
}
}
```
> Reduce response payload

- test/1-api.spec.js
- test/helpers/helpers.mock-rest-v2.js
- test/helpers/mock-data.js
- workers/loc.api/service.report.js
This PR  adds ability to read/write users settings. Basic changes:
- adds the method `updateSettings` to the main service
request:
```json
{
"auth": {
},
"method": "updateSettings",
"params": {
"settings": {
"api:key1": "value1"
}
}
}
```
response:
```json
{
"result": [
1593759447836,
"acc_ss",
null,
null,
[
1
],
null,
"SUCCESS",
null
],
"id": null
}
```
- adds the method `getSettings` to the main service
request:
```json
{
"auth": {
},
"method": "getSettings",
"params": {
"keys": ["api:key1"]
}
}
```
response:
```json
{
"result": [
[
"key1",
"value1"
]
],
"id": null
}
```
> Add ability to read-write users setting

- workers/loc.api/queue/write-data-to-stream/index.js
This PR fixes csv export with searching by a filter when the first responses are empty
> Fix csv export with searching by filter

- workers/loc.api/helpers/prepare-response.js
This PR adds filter by category for ledgers
```
{
"auth": {
},
"method": "getLedgers",
"params": {
"category": 101
}
}
```
> Add filter by category for ledgers

- test/1-api.spec.js
- test/helpers/helpers.core.js
- test/helpers/mock-data.js
- workers/loc.api/helpers/filter-models.js
This PR adds `clampMin` and `clampMax` fields to status messages derivatives. Basic changes:
- adds filtering fields to status messages derivatives
- improves status messages derivatives test coverage
- improves test helper for removing db files
- https://github.com/bitfinexcom/bfx-api-node-models/pull/57
> Add min and max clamps to status messages derivatives

- test/1-api.spec.js
- test/helpers/helpers.mock-rest-v2.js
- test/helpers/mock-data.js
- workers/loc.api/service.report.js
This PR adds the ability to generate an auth token. Basic changes:
- adds `generateToken` method to the main service
```json
{
"auth": {
},
"method": "generateToken"
}
```
Response example:
```json
{
"result": [
"pub:api:12ab12ab-12ab-12ab-12ab-12ab12ab12ab-read"
],
"id": null
}
```
- https://github.com/bitfinexcom/bfx-api-mock-srv/pull/41
> Add ability to generate auth token

- test/1-api.spec.js
- test/helpers/helpers.mock-rest-v2.js
- test/helpers/mock-data.js
- workers/loc.api/di/index.js
- workers/loc.api/helpers/check-filter-params.js
- workers/loc.api/helpers/filter.models.names.js
- workers/loc.api/helpers/limit-param.helpers.js
- workers/loc.api/helpers/prepare-response.js
- workers/loc.api/service.report.js
This PR adds the ability to fetch positions snapshot from the API to sync in the framework part for `win/loss` section. Basic changes:
- adds `getPositionsSnapshot` method to the main service
- adds the corresponding test coverage
- fixes DI (`InversifyJS`) base class checks issue:
https://github.com/inversify/InversifyJS/issues/522
https://github.com/inversify/InversifyJS/blob/master/wiki/inheritance.md#workaround-e-skip-base-class-injectable-checks
> Add ability to fetch positions snapshot

- test/1-api.spec.js
- test/helpers/helpers.mock-rest-v2.js
- test/helpers/mock-data.js
- workers/loc.api/service.report.js
This PR adds map symbols and inactive currencies into the response of the `getSymbols` method, adds the corresponding test coverage.
Example of request:
```json
{
"method": "getSymbols"
}
```
Example of response:
```json
{
"result": {
"pairs": [
"AMPUSD",
"BCCUSD"
],
"currencies": [
{
"id": "AMP",
"name": "Ampleforth",
"pool": "ETH",
"explorer": [
"https://etherscan.io",
"https://etherscan.io/address/VAL",
"https://etherscan.io/tx/VAL"
],
"symbol": "AMPL",
"walletFx": []
}
],
"inactiveSymbols": [
"GRGETH"
],
"mapSymbols": [
[
"BTCF0:USTF0",
"BTC-PERP"
],
[
"ETHF0:BTCF0",
"ETH:BTC-PERP"
]
],
"inactiveCurrencies": [
"TTT",
"DDD"
]
},
"id": null
}
```
- https://github.com/bitfinexcom/bfx-api-mock-srv/pull/43
> Add map symbols and inactive currencies into getSymbols

- test/simulate/simulate-enviroment.js
- workers/loc.api/queue/helpers/get-complete-file-name.js
- workers/loc.api/queue/helpers/utils.js
This PR changes CSV file name ending from UUID to serial number `-(1)` or `-(2)` etc
Adds an ability to simulate only grapes env using `npm run startSimulEnv -- -g`
For example:
- before `user_ledgers_FROM_Thu-Jan-01-2019_TO_Mon-Jan-04-2021_ON_Mon-Jan-04-2021-0616d514-a865-4155-bbb0-c3e7ab53d7cc.csv`
- after `user_ledgers_FROM_Thu-Jan-01-2019_TO_Mon-Jan-04-2021_ON_Mon-Jan-04-2021-(1).csv`
> Change file name ending from uuid to serial number

- test/helpers/helpers.tests.js
- test/simulate/simulate-enviroment.js
- workers/loc.api/queue/aggregator.js
- workers/loc.api/queue/helpers/get-complete-file-name.js
- workers/loc.api/queue/helpers/utils.js
- workers/loc.api/queue/processor.js
This PR adds an ability to put csv files into common folder, for each tax export, create a folder and add the 3 files inside there. Basic changes:
- Adds ability to put csv files into a common folder
- Adds test coverage for csv files storing in a common local folder
- Fixes recursive creating csv folder
- https://github.com/bitfinexcom/bfx-report/pull/203
> Add ability to put csv files into common folder

- test/helpers/helpers.tests.js
- test/simulate/simulate-enviroment.js
- workers/loc.api/queue/aggregator.js
- workers/loc.api/queue/helpers/get-complete-file-name.js
- workers/loc.api/queue/helpers/utils.js
- workers/loc.api/queue/processor.js
This PR fixes moving csv files across device.
The issue is when the user set csv folder located on different mounted disk the error `EXDEV: cross-device link not permitted` was thrown.
The solution is instead of using `fs.rename` need to first copy the file to its new location and subsequently remove the old file
- https://github.com/bitfinexcom/bfx-report/pull/204
> Fix moving csv files across device

- package.json
- workers/loc.api/helpers/get-rest.js
This PR fixes the nonce small error issues. The issue is related to the following points:
- for each request should be generated and added a new nonce for usage with the Bitfinex APIs. The nonce must be increased for the next request either an error will be thrown. This solution works fine:
https://github.com/bitfinexcom/bfx-api-node-util/blob/master/lib/nonce.js
- but we can have situations when the app can send sequential requests one by one, for example
```
1 - request with nonce: 1611303213479000 - slow
2 - request with nonce: 1611303213479001
3 - request with nonce: 1611303213479002 - fast
```
and when `1 - request` perform slower than `3 - request` and the bfx API perform `3 - request` and store its nonce, at this case we can catch the nonce error for `1 - request`
This solution …
> Fix nonce small error issues

- package.json
- test/1-api.spec.js
- test/helpers/mock-data.js
This PR bumps `bitfinex-api-node` up to `5.*` ver, related to these changes:
- https://github.com/bitfinexcom/bfx-api-node-rest/pull/78/commits/a102b86b320d8b43667ff759bc71e4bf1cbe922f
- https://github.com/bitfinexcom/bfx-api-node-models/pull/65
- https://github.com/bitfinexcom/bfx-api-mock-srv/pull/44/commits/0fdd35b47b46fffa9c42d795d34e8336ef15f38d
**Waiting for:**
- sending `bfx-api-node-models` ver 1.3.3 to `npm`
https://github.com/bitfinexcom/bfx-api-node-models/blob/master/package.json#L3
https://www.npmjs.com/package/bfx-api-node-models
- applying corresponding changes on production api_v2 side
> Bump bitfinex-api-node up to 5.*

- workers/loc.api/di/utils/decorate-injectable.js
- workers/loc.api/di/utils/index.js
- workers/loc.api/generate-csv/csv.job.data.js
- workers/loc.api/has.grc.service/index.js
- workers/loc.api/interrupter/index.js
This PR adds a helper to decorate injectable class of modules to improve readability and reduce the writing code of new modules
instead of:
```js
const {
decorate,
injectable,
inject
} = require('inversify')
const TYPES = require('../../di/types')
class SyncCollsManager {
constructor (
dao,
TABLES_NAMES,
syncSchema
) {
this.dao = dao
this.TABLES_NAMES = TABLES_NAMES
this.syncSchema = syncSchema
}
}
decorate(injectable(), SyncCollsManager)
decorate(inject(TYPES.DAO), SyncCollsManager, 0)
decorate(inject(TYPES.TABLES_NAMES), SyncCollsManager, 1)
decorate(inject(TYPES.SyncSchema), SyncCollsManager, 2)
module.exports = SyncCollsManager
```
writes as shown bellow:
```js
const { decorateInjectable } = require('../../di/utils')
const depsTypes = (TYPES) => [
TYPES.DAO,
TYPES.TABLES_NAMES, …
```
> Add helper to decorate injectable class

- package.json
This PR update the `pug` up to `3.0.2`, related to code injection vulnerability:
https://github.com/pugjs/pug/releases/tag/pug%403.0.1
https://github.com/pugjs/pug/issues/3312
https://github.com/pugjs/pug/blob/master/SECURITY.md
> Update pug up to 3.0.2

- workers/loc.api/di/app.deps.js
- workers/loc.api/generate-csv/index.js
- workers/loc.api/queue/helpers/get-local-csv-folder-paths.js
- workers/loc.api/queue/helpers/index.js
- workers/loc.api/queue/helpers/utils.js
This PR adds an ability to return the local csv folder path in response when exporting csv locally for the electron app to keep aware users
```js
{
"auth": { "token": "123token321" },
"method": "getMultipleCsv",
"params": {
"language": "en",
"multiExport": [
{
"start": 1509528489230,
"end": 1613208489230,
"limit": 500,
"timezone": "Etc/UTC",
"dateFormat": "DD-MM-YY",
"milliseconds": false,
"method": "getLedgersCsv"
}
]
}
}
```
Response example:
```js
{
"result": {
"isSaveLocaly": true,
"localCsvFolderPath": "/home/someuser/Documents/bitfinex/reports"
},
"id": null
}
```
> Add ability to return local csv folder path in response

- workers/loc.api/helpers/schema.js
This PR adds a new option for  CSVs that have 4 digit years
```json
{
"auth": {
"apiKey": "apiKey",
"apiSecret": "apiSecret"
},
"method": "getLedgersCsv",
"params": {
"dateFormat": "YYYY-MM-DD"
}
}
```
> Add a new option for  CSVs that have 4 digit years

- package.json
- test/helpers/helpers.boot.js
- test/helpers/helpers.core.js
- workers/loc.api/generate-csv/csv.job.data.js
- workers/loc.api/helpers/get-timezone-conf.js
- workers/loc.api/helpers/prepare-response.js
- workers/loc.api/helpers/utils.js
- workers/loc.api/queue/upload-to-s3/index.js
- workers/loc.api/queue/write-data-to-stream/helpers.js
This PR bumps the `yargs` up to `16` to be able to use the same `yargs`  options in the `bfx-reports-framework` repo
And bumps the `standard` up to `16`
These changes were lost when we reverted
> Bump yargs and standard

- package.json
- test/helpers/helpers.boot.js
- test/helpers/helpers.core.js
- test/helpers/helpers.tests.js
- workers/loc.api/generate-csv/csv.job.data.js
- workers/loc.api/helpers/get-timezone-conf.js
- workers/loc.api/helpers/prepare-response.js
- workers/loc.api/helpers/utils.js
- workers/loc.api/queue/aggregator.js
- workers/loc.api/queue/processor.js
- workers/loc.api/queue/upload-to-s3/index.js
- workers/loc.api/queue/write-data-to-stream/helpers.js
This PR fixes putting `csv` files into a common folder. The issue is that it doesn't work with multi-export. This feature was done with these PRs:
- https://github.com/bitfinexcom/bfx-report/pull/204
- https://github.com/bitfinexcom/bfx-reports-framework/pull/145
Adds ability to execute extra test cases for csv endpoints
- https://github.com/bitfinexcom/bfx-report/pull/229
> Fix putting csv files into common folder

- workers/loc.api/helpers/schema.js
- workers/loc.api/queue/send-mail/translations/email.yml
This PR fixes translations for emails, adds support for Spanish `es-EM`
> Fix translations for emails

- test/1-api.spec.js
- test/2-api-filter.spec.js
- test/3-report-signature.spec.js
- test/4-queue-base.spec.js
- workers/loc.api/errors/helpers.js
- workers/loc.api/errors/index.js
- workers/loc.api/helpers/check-filter-params.js
- workers/loc.api/helpers/check-params.js
- workers/loc.api/responder/index.js
- workers/loc.api/service.report.js
Rework JSON-RPC response
This PR reworks `JSON-RPC` response to follow `JSON-RPC v2.0` specification
https://www.jsonrpc.org/specification
The idea is: send a status code and status message in the grenache service in JSON. And express would just proxy it. To have all logic in one place related to detecting and logging errors
Base changes:
- Reworks `JSON-RPC` response
- Reworks common error classes
- Fixes corresponding test cases
- https://github.com/bitfinexcom/bfx-report-express/pull/16
> Rework JSON-RPC response

- test/1-api.spec.js
- test/helpers/mock-data.js
This PR adds `payment` to the `invoice list`
Payment example:
```jsonc
payment: {
txid: '1234567890qwerty',
amount: 0.123123,
currency: 'UST',
method: 'TETHERUSE',
status: 'COMPLETED',
confirmations: 5,
created_at: '2021-09-12 03:03:03',
updated_at: '2021-09-12 03:03:03',
depositId: 1234321
}
```
> Add payment to invoice list

- workers/loc.api/logger/index.js
This PR adds ability to send worker errors via ipc for the error manager of the `bfx-report-electron`. It is useful when the worker gets an error and tries to log via the `winston`. In this case, send the error to show modal dialog (on the electron side) and ask a user to open a new GitHub issue. Also adds ability to log all arguments logging via the `winston`
> Add ability to send worker error via ipc

- workers/loc.api/helpers/schema.js
- workers/loc.api/queue/send-mail/translations/email.yml
This PR adds Portuguese translations to emails
```jsonc
{
"auth": {
"apiKey": "api-key",
"apiSecret": "api-secret"
},
"method": "getLedgersCsv",
"params": {
"limit": 20,
"email": "user@mail.com",
"language": "pt-PT"
}
}
```
Email example:
- https://github.com/bitfinexcom/bfx-ext-sendgrid-js/pull/22
> Add Portuguese translations to emails

- workers/loc.api/di/app.deps.js
- workers/loc.api/di/types.js
- workers/loc.api/helpers/__test__/split-symbol-pairs.spec.js
- workers/loc.api/helpers/forex.symbs.js
- workers/loc.api/helpers/index.js
- workers/loc.api/helpers/split-symbol-pairs.js
This PR fixes symbol pair splitting. Basic changes:
- handles pairs with long characters like `tMATICM:USD`, `MATICMF0` etc
> Fix symbol pair splitting

- workers/loc.api/helpers/limit-param.helpers.js
- workers/loc.api/helpers/prepare-response.js
- workers/loc.api/service.report.js
This PR adds ability to set request limits for public API calls not more than the inner max limit: https://github.com/bitfinexcom/bfx-report/blob/cc53f7744d703cee26a88d320367b90543c9f4d3/workers/loc.api/helpers/limit-param.helpers.js#L19
This relaxation of the restriction is useful for internal requests to avoid the frequent occurrence of the rate limit error
```json
{
"auth": {
"token": "user-token"
},
"method": "getCandles",
"params": {
"start": 1651363200000,
"end": 1654041600000,
"timeframe": "1h",
"symbol": "tBTCUSD",
"limit": 10000
},
"isNotMoreThanInnerMax": true
}
```
> Use inner max limit for internal public api calls

- workers/loc.api/helpers/schema.js
- workers/loc.api/queue/send-mail/index.js
- workers/loc.api/queue/send-mail/languages.js
- workers/loc.api/queue/send-mail/translations/email.yml
This PR adds support for `pt-BR` translation, and also adds aliases to languages to follow the UI https://github.com/bitfinexcom/bfx-report-ui/blob/a48df90e9b583dc98a3646dce9963741872d728f/src/locales/i18n.js#L12
**Depend** on this PR:
- https://github.com/bitfinexcom/bfx-ext-sendgrid-js/pull/22
> Add pt-BR email translation

- test/1-api.spec.js
- test/helpers/mock-data.js
- workers/loc.api/generate-csv/csv.job.data.js
This PR adds orders metadata to csv export and also adds ones to the corresponding test case
> Add orders metadata to csv

- workers/loc.api/generate-csv/index.js
This PR fixes string `rate` normalization to csv export of `Public Funding`
Earlier we added some normalization for the string `rate` to convert to a number
https://github.com/bitfinexcom/bfx-report/blob/master/workers/loc.api/helpers/prepare-response.js#L497
https://github.com/bitfinexcom/bfx-report/blob/master/workers/loc.api/helpers/normalize-filter-params.js#L64
Need to add the corresponding normalization to csv export to have the same behavior
> Add string rate normalization to csv export

- workers/loc.api/helpers/prepare-response.js
This PR adds ability to use the inner max request limit to `api_v2` to seed up syncing data, if pass `isSyncRequest: true` flag to request params it would be used a restriction not more than `innerMax` of this map: https://github.com/bitfinexcom/bfx-report/blob/master/workers/loc.api/helpers/limit-param.helpers.js#L4
> Use inner max request limit to api v2 for syncing data

- workers/loc.api/helpers/get-data-from-api.js
- workers/loc.api/responder/index.js
This PR adds an option to not throw `ENET` error in the case when there are going to make retries to resume the internet connection. API requests should not be logged to `std error` stream when making an internal call and can have some attempts due to an internet connection issue
It's important for sync to avoid showing redundant error modal dialogs in the electron app
Related to the issue https://github.com/bitfinexcom/bfx-report-electron/issues/176
> Improve error handling

- workers/loc.api/abstract.ws.event.emitter/index.js
- workers/loc.api/helpers/get-rest.js
- workers/loc.api/responder/index.js
- workers/loc.api/service.report.js
This PR adds corresponding changes to add BFX auth token support to framework mode. Basic changes:
- Adds `invalidateAuthToken` and `generateToken` endpoints
- Adds ability to send emitBfxUnamePwdAuthRequiredToOne event by WebSockets in cases if the auth token is expired for the framework mode
- Adds ability to use dynamic getter to fetch refreshed auth token from a session in the framework mode
> Add username/pwd auth support

- test/1-api.spec.js
- test/4-queue-base.spec.js
- workers/loc.api/di/app.deps.js
- workers/loc.api/di/types.js
- workers/loc.api/errors/index.js
- workers/loc.api/generate-csv/csv-writer/index.js
- workers/loc.api/generate-csv/csv-writer/weighted-averages-report-csv-writer.js
- workers/loc.api/generate-csv/csv.job.data.js
- workers/loc.api/helpers/schema.js
- workers/loc.api/service.report.js
- workers/loc.api/weighted.averages.report/index.js
This PR adds the `Weighted Averages` report to the web version. The main part of logic moves from the `bfx-reports-framework` and the behavior is the same as in the previous PR https://github.com/bitfinexcom/bfx-reports-framework/pull/246
---
**Breaking changes**
Response example in case trades number is more than 2k (if trades number is less than 2k -> `nextPage: false`):
```jsonc
{
"jsonrpc": "2.0",
"result": {
"nextPage": 1542191602000, // trades number is less than 2k -> `nextPage: false`
"res": [
{
"symbol": "tUSTUSD",
"buyingWeightedPrice": 1.12345,
"buyingAmount": 12345,
"sellingWeightedPrice": 1.12345,
"sellingAmount": -12345,
"cumulativeWeightedPrice": 1.12345,
"cumulativeAmount": 12345
}
]
},
"id": null
}
```
---
Basic changes:
- Adds `getWeightedAveragesReport` method to the …
> Add weighted averages report to web ver

- workers/loc.api/helpers/api-errors-testers.js
This PR adds the `temporarily_unavailable` BFX error handler, it's related to issues when the main platform is under maintenance, we should cover this `bfx_api_v2` error, check the screenshot
Instead showing an error modal dialog under the electron app would show the network issue message. And also it adds some retries for fetching data as it was done earlier for the common `isENetError` checker
> Add temporarily_unavailable bfx error handler

- workers/loc.api/helpers/get-data-from-api.js
This PR adds `3` retries instead of 2 when catching `Rate Limit` error to help users to go through sync in the electron app
> Add 3 retries when catching rate limit error

- package.json
- test/1-api.spec.js
- test/helpers/helpers.mock-rest-v2.js
- test/helpers/mock-data.js
- workers/loc.api/helpers/prepare-response.js
- workers/loc.api/helpers/prepare-response/helpers/get-bfx-api-method-name.js
- workers/loc.api/helpers/prepare-response/helpers/get-params-map.js
- workers/loc.api/helpers/prepare-response/helpers/get-params-schema-name.js
- workers/loc.api/helpers/prepare-response/helpers/get-params.js
- workers/loc.api/helpers/prepare-response/helpers/get-symbol-params.js
- workers/loc.api/helpers/prepare-response/helpers/get-symbols-for-filtering.js
- workers/loc.api/helpers/prepare-response/helpers/index.js
- workers/loc.api/helpers/prepare-response/helpers/is-not-contained-same-mts.js
- workers/loc.api/helpers/prepare-response/helpers/omit-private-model-fields.js
- workers/loc.api/helpers/prepare-response/index.js
- workers/loc.api/helpers/schema.js
- workers/loc.api/service.report.js
This PR adds currency movement info endpoint https://docs.bitfinex.com/reference/movement-info. Due to the changed signatures of the `bitfinex-api-node` library methods in the new major version, to add this endpoint, the way of passing parameters to all bfx api methods is also changed/refactored
---
Basic changes:
- adds `getMovementInfo` endpoint
- reworks params processing to support new bfx rest api signatures
- bumps `bitfinex-api-node` version up to 6.0.0
- adds test coverage for `getMovementInfo` endpoint
---
```jsonc
{
"auth": {
"apiKey": "user-api-key",
"apiSecret": "user-api-secret"
},
"method": "getMovementInfo",
"params": {
"id": 12345678
}
}
```
Response example:
```jsonc
{
"jsonrpc": "2.0",
"result": {
"id": 12345678,
"currency": "UST",
"currencyName": …
```
> Add currency movement info endpoint

- workers/loc.api/helpers/api-errors-testers.js
- workers/loc.api/responder/index.js
This PR improves BFX API error handling due to the last major changes of the rest-api lib: https://github.com/bitfinexcom/bfx-api-node-rest/blame/master/lib/rest2.js#LL157C14-L170C4
---
The issue is when we make a call to `payInvoiceList` endpoint with a user who's `NOT_MERCHANT`, api send an error in the raw body `ERR_INVOICE_LIST: ERR_PAY_USER_NOT_MERCHANT` instead of `statusText`. We should handle this case
---
Basic changes:
- Improves bfx api error handling
- Extends error logging to see bfx api errors
---
Logging example:
> Improve bfx api error handling

- workers/loc.api/helpers/api-errors-testers.js
- workers/loc.api/helpers/index.js
- workers/loc.api/responder/__test__/mockedHtmlBody403.html
- workers/loc.api/responder/__test__/responder.spec.js
- workers/loc.api/responder/index.js
This PR prevents proxying all HTML of the bfx api error
---
In some cases, the bfx api may respond just HTML instead of expected json in the raw body https://github.com/bitfinexcom/bfx-api-node-rest/blame/master/lib/rest2.js#L166
For example: maintenance mode, nginx 502 `Bad Gateway` error, 403 `Forbidden` for the staging server,  check the screenshot:
---
The idea is:
- don't proxy all HTML
- extract a string of the `title` tag to use as a description of the error
- and pass it to the corresponding field of an error
---
Basic changes:
- Prevents proxying all HTML of bfx api error
- Adds `forbidden` resource error tester
- Handles `forbidden` resource error
- Adds test cases for response service for handling error with html and plain text in the  response body
--- …
> Prevent proxy all HTML of bfx api error

- workers/loc.api/weighted.averages.report/index.js
This PR decreases the limit of trades selection for the `Weighted Averages` calculation to `50k`  due to changing of the BFX API endpoint
> Decrease weighted averages limit to 50k

- workers/loc.api/weighted.averages.report/index.js
This PR Increases the limit of trades selection for the `Weighted Averages` calculation to `100k` due to changing of the `BFX API` endpoint
> Increase weighted averages limit to 100k

- workers/loc.api/weighted.averages.report/index.js
This PR adds last/first trades mts into the `weighted averages` report for the framework mode
> Add last/first trades mts into weighted averages for framework

- workers/loc.api/helpers/api-errors-testers.js
This PR fixes handling bfx api `ERR_AUTH_API: ERR_INVALID_CREDENTIALS` error to prevent showing `500 Internal Server Error` and  error modal dialog in the electron app
---
**Related** to this issue:
- https://github.com/bitfinexcom/bfx-report-electron/issues/228
> Fix handling bfx api invalid credentials error

- test/1-api.spec.js
- workers/loc.api/generate-csv/csv-writer/weighted-averages-report-csv-writer.js
- workers/loc.api/generate-csv/csv.job.data.js
- workers/loc.api/weighted.averages.report/index.js
This PR removes `cumulativeWeightedPrice` field and adds `cost`/`sale` columns to the weighted averages report
---
Basic changes:
- Removes cumulative weighted price
- Adds `cost` and `sale` columns to the weighted averages report:
```js
Cost: buying_weighted_price * buying_amount
Sale: selling_weighted_price * selling_amount
```
- Changes weighted averages report csv field order:
---
Response example:
```jsonc
{
"jsonrpc": "2.0",
"result": {
"nextPage": false,
"res": [
{
"symbol": "tBTCUSD",
"buyingWeightedPrice": 25163.76585333,
"buyingAmount": 552.97181669,
"sellingWeightedPrice": 25157.45514297,
"sellingAmount": -552.97181669,
"cumulativeAmount": 0,
"cost": 13914853.318677677,
"sale": -13911363.673705304,
"firstTradeMts": 1627704333998,
"lastTradeMts": 1690223080583
}
]
},
"id": null …
```
> Remove cumulative weighted price and add cost/sale columns

- workers/loc.api/helpers/date-param.helpers.js
- workers/loc.api/helpers/index.js
- workers/loc.api/helpers/prepare-response/helpers/get-params.js
This PR fixes `start` timestamp to be at least `Date.UTC(2013)` = `1356998400000` ms
---
The issue is the following:
- some restrictions of the bfx-api are changed for `Funding Credits History`
- now if we set `end: Date.now()` and `start: 0` throws `Internal Server Error` from `bfx-rest` side
- it's an issue for the `sync` mode (as we start syncing with `0`) and setting the default value for requests
---
Related to these issues:
- https://github.com/bitfinexcom/bfx-report-electron/issues/232
- https://github.com/bitfinexcom/bfx-report-electron/issues/233
- https://github.com/bitfinexcom/bfx-report-electron/issues/234
> Fix start timestamp to be at least 2013

- workers/loc.api/responder/index.js
This PR enhances the error message of the `json rpc` response. The idea is to have extra data in case we catch an error from BFX API side and on the UI use a transparent error message  which can contain BFX API error reasons
```js
res?.error?.message
```
instead of proxy whole error object for error representation
---
Earlier we can have the following `json rpc` cases for errors:
- if internal error:
```jsonc 
{
"jsonrpc": "2.0",
"error": {
"code": 500,
"message": "Internal Server Error",
"data": null
},
"id": null
}
```
- if error came from BFX API:
```jsonc
{
"jsonrpc": "2.0",
"error": {
"code": 500,
"message": "Internal Server Error",
"data": {
"bfxApiErrorMessage": {
"bfxApiStatus": 500,
"bfxApiStatusText": "Internal Server Error",
"bfxApiRawBodyCode": "Code is not available", …
```
> Fix bfx api error response

- workers/loc.api/abstract.ws.event.emitter/index.js
- workers/loc.api/helpers/api-errors-testers.js
- workers/loc.api/helpers/index.js
- workers/loc.api/responder/index.js
This PR informs user that the platform is marked in `maintenance` mode by WS, in the framework mode
---
The idea is the following:
- if an error `["error", 20060, "maintenance"]` https://docs.bitfinex.com/docs/rest-general catches when fetching data from bfx api
- send `emitMaintenanceTurnedOn` event by WS
- also adds `emitMaintenanceTurnedOff` event which will be sent from the framework part in case maintenance mode is turned off
- in UI if the event is gotten show a corresponding message to inform the user that some features are unavailable
> Inform user that platform is marked in maintenance mode

- workers/loc.api/helpers/utils.js
This PR removes `lodash.transform` usage as redundant and not used anywhere. It's the first part of the migration from the `lodash` lib to bfx internal one
> Remove lodash.transform usage

- workers/loc.api/generate-csv/csv-writer/helpers/index.js
- workers/loc.api/generate-csv/csv-writer/weighted-averages-report-csv-writer.js
- workers/loc.api/generate-csv/csv.job.data.js
This PR fixes `MaxListenersExceededWarning` for complicated `csv` reports using the `transform` csv stream waiting for writing to complete `one by one` instead of pipelining all csv streams `simultaneously`
Also, the corresponding approach aims to use in the framework
> Prevent max listeners exceeded warning

- package.json
- workers/loc.api/helpers/check-params.js
- workers/loc.api/helpers/date-param.helpers.js
- workers/loc.api/helpers/get-data-from-api.js
- workers/loc.api/helpers/normalize-filter-params.js
- workers/loc.api/helpers/prepare-response/helpers/get-params.js
- workers/loc.api/helpers/prepare-response/helpers/omit-private-model-fields.js
- workers/loc.api/helpers/schema.js
- workers/loc.api/queue/processor.js
- workers/loc.api/queue/write-data-to-stream/data-normalizer.js
- workers/loc.api/queue/write-data-to-stream/helpers.js
- workers/loc.api/queue/write-data-to-stream/index.js
This PR removes lodash `omit`, `cloneDeep`, `min`, `max` usage. It's the next part of the migration from the `lodash` lib to bfx internal one
> Remove lodash usage

- .github/workflows/ci.yml
- .github/workflows/test-report.yml
This PR adds test runner and report workflows to GitHub actions
---
Report examples of test:
- successful: https://github.com/ZIMkaRU/bfx-report/pull/2/checks?check_run_id=17529429034
- failed: https://github.com/ZIMkaRU/bfx-report/runs/17528440663
> Add test runner and report to GitHub actions

- workers/loc.api/helpers/prepare-response/helpers/is-not-contained-same-mts.js
This PR fixes double requests while syncing `candles`
---
The issue is: when we sync data in the framework mode, candles request can give only one item, in this case, we shouldn't process the part of logic with handling of containing the same timestamps in all items
> Fix double requests while syncing candles

- workers/loc.api/helpers/api-errors-testers.js
This PR adds detection for BFX auth error
---
There can be cases with getting `ERR_AUTH_API: ERR_TOKEN_ALREADY_USED` error from the BFX API side
We have several issues with the same error:
- https://github.com/bitfinexcom/bfx-report-electron/issues/281
- https://github.com/bitfinexcom/bfx-report-electron/issues/313
It should be detected as an auth error and processed with `401` instead `500` at least do not show a bug report modal window in the electron app. And these changes are enough to cover it
---
On the other hand, the mentioned issue related to 2fa:
- when need to set google auth code
- UI doesn't block btn after the first push
- and the user can make 2 requests accidentally
- and for auth token generation will be used otp token 2 times
- as a result `ERR_AUTH_API: …
> Add detection for bfx auth error

- workers/loc.api/generate-report-file/pdf-writer/index.js
- workers/loc.api/generate-report-file/pdf-writer/templates/base.pug
- workers/loc.api/generate-report-file/pdf-writer/templates/style.css
This PR moves the `Statement Details` section under the logo for pdf reports
---
---
- https://github.com/bitfinexcom/bfx-ext-pdf-js/pull/4
> Move statement details section under logo for pdf reports

- workers/loc.api/helpers/grc-bfx-req.js
This PR sets `90sec` timeout for grc requests to have the same timeout as for api requests
> Set 90sec timeout for grc requests

- .github/workflows/ci.yml
- .github/workflows/test-report.yml
This PR updates GH Actions to use Nodejs v20
---
Solution:
- as `dorny/test-reporter` GH Action is stuck with the update to support `actions/upload-artifact@v4`
- turns off downloading test results managed `dorny/test-reporter` with removing `artifact` options
- adds additional downloading step before `dorny/test-reporter` using `actions/download-artifact@v4` actions
- and use `actions/upload-artifact@v4` everywhere
---
**Notes:**
- after opening PR against `master` the unit tests will be triggered, but `Test Report` will fail because the GH Actions don't want to take the last incoming changes of the corresponding workflow file and uses already existing changes in the master branch that are incompatible. And after merging in the next release iteration, everything should work as expected
- …
> Update gh actions to use nodejs v20

- workers/loc.api/helpers/get-data-from-api.js
This PR adds handling unexpected BFX API errors
---
Adds `3` retries with a timeout `10sec` if catches any unexpected errors during report generation or db sync in framework mode
---
**Related** to these issues:
- https://github.com/bitfinexcom/bfx-report-electron/issues/355
- https://github.com/bitfinexcom/bfx-report-electron/issues/354
> Handle unexpected BFX API errors

- workers/loc.api/responder/index.js
This PR extends error logs for sync proc
---
The idea is to add `serializedError` field to the error object with a serialized error string that contains composed error metadata for easier debugging of the user's error reports. This field will be used for logging in case catching error occurs during sync in the framework mode
> Extend error logs for sync proc

- .github/workflows/ci.yml
This PR updates GitHub `action/setup-node` to `v4` to resolve `Node.js 16 actions are deprecated`
---
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
> Update gh action setup-node to v4

- .github/dependabot.yml
- package.json
This PR adds `dependabot` config for the ability to open new PRs against the `staging` branch
Also bumps `pug` version to `3.0.3` to resolve this PR:
- https://github.com/bitfinexcom/bfx-report/pull/376
There is a security improvement https://github.com/pugjs/pug/pull/3438
> Add dependabot config and update pug

- workers/loc.api/queue/write-data-to-stream/helpers.js
This PR adds `CSV`/`PDF` formatter for the tax report `source` field to follow the UI view, eg show `AIRDROP_ON_WALLET` as `Airdrop on wallet`
> Add csv formatter for tax report source field

- workers/api.service.report.wrk.js
- workers/loc.api/generate-report-file/index.js
- workers/loc.api/service.report.js
This PR removes deprecated methods and fields without breaking the logic and UI functionality
---
Basic changes:
- remove deprecated isAddedUniqueEndingToCsvName config field
- remove deprecated report exporting metadata fields
- remove deprecated main service methods
> Remove deprecated methods and fields

- workers/loc.api/helpers/api-errors-testers.js
- workers/loc.api/helpers/index.js
This PR adds `socket hang up` error processing as `ENet` error
---
Related to this issue:
- https://github.com/bitfinexcom/bfx-report-electron/issues/400
> Add socket hang up error processing

- workers/loc.api/helpers/api-errors-testers.js
- workers/loc.api/helpers/index.js
This PR adds common net `net::ERR_` error processing as `ENet` error
---
Related to these issues:
- https://github.com/bitfinexcom/bfx-report-electron/issues/383
- https://github.com/bitfinexcom/bfx-report-electron/issues/362
> Add common net error processing

- workers/loc.api/helpers/api-errors-testers.js
This PR fixes `node-fetch` timeout error processing for slow network connection
---
> Fix node-fetch timeout error processing

- workers/loc.api/helpers/get-data-from-api.js
This PR improves the interruption flow of getting data from the bfx api for the tax report
---
Base change:
- provides event-driven flow after delay processing
> Improve interruption for tax report

- workers/loc.api/responder/index.js
This PR extends data logging by showing public request params to simplify debugging BFX API issues
---
Example of simulated issue and log:
> Extend data logging by showing public request params

- workers/loc.api/helpers/schema.js
- workers/loc.api/i18next/index.js
This PR removes `language` schema param check and adds `en` fallback language to prevent returning the translation key `key.nestedKey.etc` if a value is missing for a certain language and adds the ability to try to take one from the default `en` translation file as it was done in the electron app https://github.com/bitfinexcom/bfx-report-electron/pull/426
> Remove language schema param check and add en fallback lng

- .github/workflows/ci.yml
- workers/loc.api/generate-report-file/pdf-writer/index.js
- workers/loc.api/generate-report-file/pdf-writer/templates/base.pug
This PR migrates from `html-pdf` to `puppeteer` for pdf creation as the first one repo is not maintained anymore. Adds minor changes for the framework mode
> Migrate from html-pdf to puppeteer for pdf creation

- workers/loc.api/helpers/get-data-from-api.js
- workers/loc.api/helpers/get-data-from-api/helpers/calc-back-off-and-jittered-delay.js
- workers/loc.api/helpers/get-data-from-api/helpers/delay.js
- workers/loc.api/helpers/get-data-from-api/helpers/get-empty-arr-res.js
- workers/loc.api/helpers/get-data-from-api/helpers/get-random-int.js
- workers/loc.api/helpers/get-data-from-api/helpers/index.js
- workers/loc.api/helpers/get-data-from-api/helpers/is-interrupted.js
- workers/loc.api/helpers/get-data-from-api/index.js
This PR adds exponential backoff and jitter for bfx-api requests to improve `Rate Limit` bypassing
---
Here we implement `Decorrelated Jitter` described in AWS article https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ And add a small improvement to shift the starting point of jitter for each iteration. In practice, it helps better to move through the `Rate Limit` for the Sync and Tax Report
> Add backoff and jitter for bfx-api requests
