test/2-sync-mode-sqlite.spec.js, workers/loc.api/helpers/get-csv-job-data.js, workers/loc.api/sync/data.inserter/api.middleware.handler.after.js, workers/loc.api/sync/data.inserter/api.middleware.js, workers/loc.api/sync/data.inserter/halpers.js, workers/loc.api/sync/data.inserter/index.js, workers/loc.api/sync/schema.js
This PR improves position history data for the sync mode:
- adds `Profit & Loss` calculation
- adds `Profit & Loss Percentage` calculation
- adds closing price
=> Improve position history data for sync mode

workers/loc.api/helpers/api-errors-testers.js, workers/loc.api/helpers/check-params.js, workers/loc.api/helpers/date-param.helpers.js, workers/loc.api/helpers/get-rest.js, workers/loc.api/helpers/get-timezone-conf.js, workers/loc.api/helpers/has-job-in-queue-with-status-by.js, workers/loc.api/helpers/index.js, workers/loc.api/helpers/limit-param.helpers.js, workers/loc.api/helpers/prepare-response.js, workers/loc.api/helpers/utils.js
This PR splits the main helpers `workers/loc.api/helpers/index.js` into different modules and simplify `prepare-response` helper
=> Refactor main helpers

test/1-api.spec.js, test/3-queue-base.spec.js, test/helpers/helpers.mock-rest-v2.js, test/helpers/mock-data.js, workers/loc.api/helpers/get-csv-job-data.js, workers/loc.api/helpers/schema.js, workers/loc.api/queue/helpers.js, workers/loc.api/service.report.js
This PR adds active positions without the sync mode (for sync mode requests will be sent directly to the `api_v2`)
* This PR depends on this PR: [bitfinexcom/bfx-api-node-rest#21](https://github.com/bitfinexcom/bfx-api-node-rest/pull/21)
=> Add active positions

workers/loc.api/errors/index.js, workers/loc.api/sync/dao/dao.js, workers/loc.api/sync/dao/dao.sqlite.js, workers/loc.api/sync/dao/helpers/get-insertable-array-objects-filter.js, workers/loc.api/sync/dao/helpers/get-limit-query.js, workers/loc.api/sync/dao/helpers/get-order-query.js, workers/loc.api/sync/dao/helpers/get-placeholders-query.js, workers/loc.api/sync/dao/helpers/get-projection-query.js, workers/loc.api/sync/dao/helpers/get-unique-index-query.js, workers/loc.api/sync/dao/helpers/get-where-query.js, workers/loc.api/sync/dao/helpers/index.js, workers/loc.api/sync/dao/helpers/serialization.js, workers/loc.api/sync/dao/helpers/utils.js
This PR splits the `DAO` module `workers/loc.api/sync/dao` into different helper modules and moves errors to errors module
=> Refactor DAO

workers/loc.api/errors/index.js, workers/loc.api/helpers/bfx.factory.js, workers/loc.api/helpers/check-params.js, workers/loc.api/helpers/date-param.helpers.js, workers/loc.api/helpers/get-csv-job-data.js, workers/loc.api/helpers/get-rest.js, workers/loc.api/helpers/has-job-in-queue-with-status-by.js, workers/loc.api/helpers/prepare-response.js, workers/loc.api/helpers/utils.js, workers/loc.api/service.report.js, workers/loc.api/service.report.mediator.js
This PR moves custom errors to the errors module
=> Refactoring errors

workers/loc.api/sync/dao/dao.sqlite.js
This PR adds `exclude`, `isExcludePrivate` params to the `SqliteDAO` `getElemsInCollBy` method
=> Improve SqliteDAO

workers/loc.api/helpers/get-csv-job-data.js
Add fields as to export csv for public funding
=> add option as to export public funding csv

workers/loc.api/helpers/get-csv-job-data.js, workers/loc.api/sync/schema.js
This PR:
- changes public trades model for supporting public funding
- changes the name of the public funding symbol field csv
- fixes checking isTradingPair for supporting symbol array
=> Change public trades model

workers/loc.api/sync/data.inserter/index.js, workers/loc.api/sync/schema.js
This PR improves the wallets sync. When the sync is stoped (for example, the electron app is closed) then we need to continue sync of wallets from the last row of the DB
=> Improve wallets sync

workers/loc.api/helpers/get-csv-job-data.js, workers/loc.api/helpers/limit-param.helpers.js, workers/loc.api/queue/helpers.js
This PR corrects the export title of public funding. Before it was `username_public_trades_FROM_Mon-Mar-11-2019_TO_Mon-Mar-25-2019_ON_2019-03-25T08-28-11.256Z`, now it is `username_public_funding_FROM...`
=> Correct export title of public funding

workers/loc.api/service.report.mediator.js
This PR improves `getWallets` method of the sync mode, adds an ability to return an async response
=> Improve getWallets method of sync mode

workers/loc.api/helpers/check-job-and-get-user-data.js, workers/loc.api/helpers/get-csv-job-data.js, workers/loc.api/helpers/index.js, workers/loc.api/queue/helpers.js, workers/loc.api/queue/processor.js
This PR adds an ability to expand csv export for the [bfx-reports-framework](https://github.com/bitfinexcom/bfx-reports-framework/pull/10)
=> Add ability to expand csv export for bfx-reports-framework

workers/loc.api/service.report.mediator.js
This PR adds an ability to omit wallets if balance is 0
=> Omit wallets if balance is 0

workers/api.service.report.wrk.js
This PR saves the correct service initialization flow
=> Save correct service initialization flow

workers/loc.api/service.report.js
=> Add futures pairs

workers/loc.api/sync/data.inserter/api.middleware.handler.after.js, workers/loc.api/sync/data.inserter/helpers/search-close-price-and-sum-amount.js
This PR improves `pl` and `pl%` calculation of `positionsHistory` when the sync is being done
=> Improve pl and pl% calculation of positionsHistory

package.json
Add `bfx-facs-interval` as a dependency as it gives an error without it.
=> add bfx-facs-interval

workers/loc.api/di/app.deps.js, workers/loc.api/di/types.js, workers/loc.api/generate-csv/csv.job.data.js, workers/loc.api/generate-csv/index.js, workers/loc.api/helpers/index.js
This PR improves `CsvJobData` module
=> Improve CsvJobData module

test/1-api.spec.js, test/helpers/mock-data.js, workers/loc.api/generate-csv/csv.job.data.js
This PR adds `collateral`, `collateralMin`, `meta` fields to active positions
=> Add new fields to active position

workers/loc.api/helpers/api-errors-testers.js, workers/loc.api/responder/index.js
This PR improves handling and logging auth error
**Depends** on this PR: [bfx-report-express#7](https://github.com/bitfinexcom/bfx-report-express/pull/7)
=> Improve handling auth error

workers/loc.api/helpers/filter-models.js, workers/loc.api/helpers/filter.models.names.js
This PR adds an ability to filter status messages
=> Add ability to filter status messages

config/service.report.json.example, workers/loc.api/di/app.deps.js, workers/loc.api/queue/aggregator.js, workers/loc.api/queue/helpers/get-complete-file-name.js, workers/loc.api/queue/helpers/utils.js, workers/loc.api/queue/upload-to-s3/index.js
This PR adds an option to add a unique ending to csv filename
- If set `"isAddedUniqueEndingToCsvName": true` to `service.report.json` config will be added unique ending to csv filename
=> Add unique ending to csv filename

.npmrc, package.json, workers/loc.api/helpers/__test__/filter-response.spec.js, workers/loc.api/helpers/filter-response.js, workers/loc.api/helpers/prepare-response.js
This PR adds an ability does not consider capital letters on filters
=> Add ability does not consider capital letters on filters

workers/loc.api/helpers/limit-param.helpers.js, workers/loc.api/helpers/prepare-response.js
This PR fixes an issue on many responses with the same `mts`
The issue is when a user that hits this limit: https://github.com/bitfinexcom/bfx-report/blob/0386cd24204fb5f0fbf040155d1d49c3ef20e802/workers/loc.api/helpers/limit-param.helpers.js#L8
Applies the following logic:
- when hit `max` and all entries have the same `mts`, make a new request with `innerMax` value
```
const _methodsLimits = {
tickersHistory: { default: 100, max: 250, innerMax: 10000 },
positionsHistory: { default: 25, max: 50, innerMax: 10000 },
positionsAudit: { default: 100, max: 250, innerMax: 2500 },
ledgers: { default: 250, max: 500, innerMax: 2500 },
trades: { default: 500, max: 1000, innerMax: 2500 },
orderTrades: { default: 500, max: 1000, innerMax: 2500 },
fundingTrades: { default: 500, max: 1000, innerMax: …
```
=> Fix issue on many responses with same mts

workers/loc.api/helpers/get-data-from-api.js, workers/loc.api/helpers/index.js, workers/loc.api/queue/write-data-to-stream/helpers.js, workers/loc.api/queue/write-data-to-stream/index.js
This PR adds an ability to pass middleware to getting data from the `api_v2`
=> Add ability to pass middleware to getting data from api

workers/loc.api/helpers/limit-param.helpers.js
This PR improves max limits to `api_v2`
=> Improve max limits to api_v2

workers/loc.api/helpers/limit-param.helpers.js
=> Change limit for orders

workers/loc.api/helpers/limit-param.helpers.js
Change movements inner max to 1K
=> Change movements inner max to 1K

workers/loc.api/helpers/prepare-response.js, workers/loc.api/service.report.js
This PR fixes `api_v2` response fields parsing to process before filtering
=> Fix api response fields parsing to process before filtering

package.json, workers/loc.api/generate-csv/csv.job.data.js
Add id to ledgers when csv export
=> Add id to ledgers

workers/loc.api/generate-csv/csv.job.data.js, workers/loc.api/helpers/index.js, workers/loc.api/helpers/utils.js, workers/loc.api/service.report.js
This PR adds positions audit id parser to convert string array to integer array
=> Add positions audit id parser

package.json, workers/loc.api/service.report.js
Remove wallets history from hosted version as this endpoint is not working fine.
=> Fix wallets export

workers/loc.api/helpers/prepare-response.js
This PR fixes margin funding payment filtering by symbols array
=> Fix margin funding payment filtering by symbols array

package.json, test/1-api.spec.js, test/2-api-filter.spec.js, test/3-report-signature.spec.js, test/4-queue-base.spec.js, test/5-queue-load.spec.js, workers/loc.api/di/app.deps.js, workers/loc.api/generate-csv/csv.job.data.js, workers/loc.api/generate-csv/index.js, workers/loc.api/helpers/check-job-and-get-user-data.js, workers/loc.api/helpers/has-job-in-queue-with-status-by.js, workers/loc.api/service.report.js
This PR adds support for a new auth way. Basic changes:
- remove the legacy methods: `login`, `getEmail`
- adds `verifyUser` method
- improves test coverage
**Depends** on this PR https://github.com/bitfinexcom/bfx-report-express/pull/9
=> New auth way

workers/loc.api/queue/helpers/get-complete-file-name.js
This PR adds an ability to specify csv file name
- https://github.com/bitfinexcom/bfx-report/pull/174
=> Add ability to specify csv file name

workers/loc.api/helpers/filter-models.js
This PR fixes filter models to allow users to filter by ip field using `like` operator
=> Fix filter models

workers/loc.api/helpers/index.js, workers/loc.api/helpers/normalize-filter-params.js, workers/loc.api/helpers/prepare-response.js
This PR fixes public trades filtering, as solution adds the ability to normalize `rate` filtering property to convert from string to number
=> Fix public trades filtering

workers/loc.api/helpers/index.js, workers/loc.api/helpers/normalize-filter-params.js, workers/loc.api/helpers/prepare-response.js, workers/loc.api/queue/write-data-to-stream/index.js
Update master with last funding filtering added to beta
=> Add funding filtering

workers/loc.api/generate-csv/csv.job.data.js, workers/loc.api/helpers/__test__/split-symbol-pairs.spec.js, workers/loc.api/helpers/index.js, workers/loc.api/helpers/split-symbol-pairs.js, workers/loc.api/queue/write-data-to-stream/data-normalizer.js, workers/loc.api/queue/write-data-to-stream/helpers.js
This PR adds fee perc to trades csv exports
=> Add fee perc to trades csv exports

workers/loc.api/di/app.deps.js, workers/loc.api/di/types.js, workers/loc.api/helpers/get-data-from-api.js, workers/loc.api/interrupter/index.js
This PR adds an ability to interrupt API calls when there catch rate limit error and await delay to the next trying
=> Add ability to interrupt API calls

package.json, test/helpers/helpers.boot.js, test/helpers/helpers.core.js, workers/loc.api/generate-csv/csv.job.data.js, workers/loc.api/helpers/get-timezone-conf.js, workers/loc.api/helpers/prepare-response.js, workers/loc.api/helpers/utils.js, workers/loc.api/queue/upload-to-s3/index.js, workers/loc.api/queue/write-data-to-stream/helpers.js
This PR increases the `standard` version up to 16
=> Increase standard version up to 16

package.json, test/helpers/helpers.boot.js, test/helpers/helpers.core.js, workers/loc.api/generate-csv/csv.job.data.js, workers/loc.api/helpers/get-rest.js, workers/loc.api/helpers/get-timezone-conf.js, workers/loc.api/helpers/prepare-response.js, workers/loc.api/helpers/utils.js, workers/loc.api/queue/upload-to-s3/index.js, workers/loc.api/queue/write-data-to-stream/helpers.js
Reverts bitfinexcom/bfx-report#209 as proxy update is not working as expected as apply has been redefined.
=> Revert "Update Master with Beta"

workers/loc.api/helpers/get-rest.js
This PR fixes bfx rest proxy to handle `sync` and `async` functions, solves the issue related to fetching the `Currencies`
=> Fix bfx rest proxy to handle sync and async fn

README.md, config/service.report.json.example, workers/loc.api/helpers/get-rest.js
This PR removes the `company` setting due to no longer needed
=> Remove company setting

test/1-api.spec.js, test/2-api-filter.spec.js, test/helpers/mock-data.js, workers/loc.api/generate-csv/csv.job.data.js, workers/loc.api/helpers/filter-models.js
This PR adds movements note https://github.com/bitfinexcom/bfx-api-node-models/pull/64 to reports
=> Add movements note

package.json, test/1-api.spec.js, test/2-api-filter.spec.js, test/helpers/mock-data.js, workers/loc.api/di/utils/decorate-injectable.js, workers/loc.api/di/utils/index.js, workers/loc.api/generate-csv/csv.job.data.js, workers/loc.api/has.grc.service/index.js, workers/loc.api/helpers/filter-models.js, workers/loc.api/interrupter/index.js
Send last changes in beta to master
=> Update master with Beta

package.json, test/1-api.spec.js, test/2-api-filter.spec.js, test/helpers/mock-data.js, workers/loc.api/di/utils/decorate-injectable.js, workers/loc.api/di/utils/index.js, workers/loc.api/generate-csv/csv.job.data.js, workers/loc.api/has.grc.service/index.js, workers/loc.api/helpers/filter-models.js, workers/loc.api/interrupter/index.js
Reverts bitfinexcom/bfx-report#221
=> Update Bitfinex api node to version 5

package.json, test/1-api.spec.js, test/2-api-filter.spec.js, test/helpers/mock-data.js, workers/loc.api/di/utils/decorate-injectable.js, workers/loc.api/di/utils/index.js, workers/loc.api/generate-csv/csv.job.data.js, workers/loc.api/has.grc.service/index.js, workers/loc.api/helpers/filter-models.js, workers/loc.api/interrupter/index.js
Send api node version 5 to production
=> Update production with Api node version 5

package.json, workers/loc.api/helpers/schema.js, workers/loc.api/queue/send-mail/translations/email.yml
This PR adds Turkish as a possible language
=> Add tr language

test/1-api.spec.js, test/4-queue-base.spec.js, test/helpers/helpers.mock-rest-v2.js, test/helpers/mock-data.js, workers/loc.api/generate-csv/csv.job.data.js, workers/loc.api/helpers/api-errors-testers.js, workers/loc.api/helpers/filter-models.js, workers/loc.api/helpers/filter.models.names.js, workers/loc.api/helpers/index.js, workers/loc.api/helpers/limit-param.helpers.js, workers/loc.api/helpers/prepare-response.js, workers/loc.api/helpers/schema.js, workers/loc.api/responder/index.js, workers/loc.api/service.report.js
This PR adds a new endpoint to the hosted version called `pay invoice list`, the backend endpoint is: https://docs.bitfinex.com/reference#invoice-list
Basic changes:
- adds `getPayInvoiceList()` method into the main service, can recive the following params:
```jsonc
"params": {
"start": 123, // integer
"end": 321, // integer
"limit": 20, // integer
"id": "invoice-string-id", // string
"symbol": "USD" // string or array string
}
```
- adds `getPayInvoiceListCsv()` method into the main service
- adds support the following filters:
```js
{
id: { type: 'string' },
t: { type: 'integer' },
duration: { type: 'number' },
amount: { type: 'number' },
currency: { type: 'string' },
orderId: { type: 'string' },
webhook: { type: 'string' },
redirectUrl: { type: …
```
=> Add pay invoice list

test/1-api.spec.js, test/4-queue-base.spec.js, test/helpers/helpers.mock-rest-v2.js, test/helpers/mock-data.js, workers/loc.api/generate-csv/csv.job.data.js, workers/loc.api/helpers/api-errors-testers.js, workers/loc.api/helpers/filter-models.js, workers/loc.api/helpers/filter.models.names.js, workers/loc.api/helpers/get-data-from-api.js, workers/loc.api/helpers/index.js, workers/loc.api/helpers/limit-param.helpers.js, workers/loc.api/helpers/prepare-response.js, workers/loc.api/helpers/schema.js, workers/loc.api/responder/index.js, workers/loc.api/service.report.js
This PR improves handling of the pay invoice list. Basic changes:
- adds string id for testing of the pay invoice list
- adds ability to handle the case when user is not merchant for sync mode
- https://github.com/bitfinexcom/bfx-report/pull/242
=> Improve handling of pay invoice list

workers/loc.api/logger/index.js
This PR adds a stack trace to the message. There was seen a case when stack trace wasn't shown in the log message
=> Improve logger

workers/loc.api/abstract.ws.event.emitter/index.js, workers/loc.api/di/app.deps.js, workers/loc.api/di/helpers/index.js, workers/loc.api/di/types.js, workers/loc.api/errors/index.js, workers/loc.api/helpers/get-data-from-api.js, workers/loc.api/queue/write-data-to-stream/index.js
This PR adds the ability to send events by WS to notify users when fetching data from bfx_api_v2 is paused due broken internet connection. This implementation is the main part of implementation on the reports-framework side
=> Notify sync is being paused until connection is resumed by ws

workers/loc.api/helpers/api-errors-testers.js
This PR adds enet errors for reconnection when fetching data from BFX api_v2
=> Add enet errors for reconnection

package.json, workers/loc.api/helpers/prepare-response.js, workers/loc.api/helpers/utils.js, workers/loc.api/queue/upload-to-s3/index.js
This PR releases version to beta, bumps up dependency versions to fix vulnerabilities
=> Release version to beta

workers/loc.api/helpers/get-data-from-api.js
This PR fixes getting data from `BFX API` with undefined args
---
- https://github.com/bitfinexcom/lib-js-util-base/pull/15
=> Fix getting data from api with undefined args

config/service.report.json.example, workers/loc.api/queue/helpers/get-report-content-type.js, workers/loc.api/queue/upload-to-s3/index.js
This PR fixes the issue with isCompress that had С Cyrillic letter "Es" instead of Latin C
=> Fix isCompress

workers/loc.api/generate-report-file/pdf-writer/translations.yml
This PR adds missing translations for pdf reports
=> Add missing translations for pdf reports

workers/loc.api/helpers/get-data-from-api.js
This PR speeds up auth in case token expiration to prevent redundant awaiting
=> Speed up auth in case token expiration

.github/workflows/ci.yml, test/1-api.spec.js, test/2-api-filter.spec.js, test/3-report-signature.spec.js
This PR adds `3` retries for the test run before it fails. Also increases `timeouts` for mocha hooks
=> Add several retries for the test run before it fails

workers/loc.api/helpers/prepare-response/helpers/is-not-contained-same-mts.js
This PR strengthens consistency data for export
---
**Related** to this PR:
- https://github.com/bitfinexcom/bfx-report/pull/343
=> Strengthen consistency data for export

workers/loc.api/bfx.api.router/index.js, workers/loc.api/generate-report-file/csv-writer/weighted-averages-report-csv-writer.js, workers/loc.api/helpers/get-data-from-api.js, workers/loc.api/helpers/get-rest.js, workers/loc.api/helpers/prepare-response/index.js, workers/loc.api/queue/write-data-to-stream/index.js, workers/loc.api/service.report.js
This PR adds interruption ability in case rate limit. When getting `Rate Limit` or `cool down` due to `Rate Limit` for 1min occurs, it needs to provide a feature to interrupt the tax report and sync being processed
=> Add interruption ability in case rate limit

test/helpers/helpers.core.js
This PR improves db file cleanups for test coverage hooks
---
Related to this PR:
- https://github.com/bitfinexcom/lokue/pull/3
=> Improve db file cleanups for test coverage hooks

test/1-api.spec.js, workers/loc.api/responder/index.js
This PR fixes error metadata processing
---
**Related** to this test pipeline:
- https://github.com/bitfinexcom/bfx-report/actions/runs/12114987593/job/33772854879
=> Fix error metadata processing

package.json
This PR updates deps with moderate-level vulnerabilities
=> Update deps with moderate-level vulnerabilities

workers/loc.api/generate-report-file/pdf-writer/templates/style.css
This PR adds warning message styles for pdf reports
=> Add warning message styles for pdf reports
